Axel Soler Portfolio
AxelSoler/Axel-Soler-Portfolio pull request #1
Opened 2022-03-16 19:46 UTC by AxelSoler

2022-03-16 22:43 UTC, AnselemOdims requested changes
### Hi @AxelSoler , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-16 22:43 UTC, AnselemOdims commented on Portfolio.html
> +        <h3>My Logo</h3>
- [ ] Please change the `h3` to `a` tag so that the logo can be linked to the home page in a multi-page website

2022-03-16 22:43 UTC, AnselemOdims commented on Portfolio.html
> +        <img class="tools" src="../Axel-Soler-Portfolio/images/Union.png" alt="">
- [ ] Kindly wrap the hamburger in a `nav` tag
- [ ] Also, please make sure the hamburger is included in your design and the toolbar section matches the original design

### Your Design
![image](https://user-images.githubusercontent.com/43995830/158703227-03f40dfd-36a5-4724-b51f-0c098ec6742a.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/158703165-d237905b-9f8d-410e-9570-9e8a5504ff45.png)

2022-03-16 22:43 UTC, AnselemOdims commented on Portfolio.html
> +    <div class="headline">
- [ ] Kindly change the `div` to a `section` for semantic purposes.

2022-03-16 22:43 UTC, AnselemOdims commented on style.css
> +  margin-right: 150px;
- [ ] Please kindly ensure that the paragraph matches the design. You can remove the margins around the paragraph so it looks more like the original design

### Your Design
![image](https://user-images.githubusercontent.com/43995830/158702872-507e2080-28f2-4976-aebf-b853a93ca281.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/158702932-6a3a10cb-8cdd-4bd4-b8f8-278aa290791e.png)

2022-03-16 23:32 UTC, AxelSoler commented
hello @AnselemOdims, thank you for the feedback.
what do you mean by 'make sure the hamburger is included in your design and the toolbar section matches the original design', I don't know what exactly are you talking about

2022-03-16 23:35 UTC, AxelSoler commented
and can you check the pull request again? thank you very much

2022-03-17 14:53 UTC, AnselemOdims approved these changes
### Hi  @AxelSoler 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 14:53 UTC, AnselemOdims commented on Portfolio.html
> +            <img class="tools" src="../Axel-Soler-Portfolio/images/Union.png" alt="hamburguer">
- [ ][OPTIONAL] At the moment, this hamburger icon is not being displayed because the relative path is not correct. Kindly use `./images/Union.png`

2022-03-17 16:09 UTC, merged